### ISSUE TITLE
Code samples unreadable at : http://ember-cli.com/user-guide/#naming-conventions

### ISSUE THREAD

**Issue by shearichard** [ember-cli/ember-cli.github.io#45] opened 2016-02-04 07:34 UTC
All of the code samples at http://ember-cli.com/user-guide/#naming-conventions are blackish text on a blackish background .

**Comment by trabus** [comment] 2016-02-04 07:39
Closing, this appears to be a duplicate of #44 I'm guessing the missing font is somehow related.

**Comment by leo** [comment] 2016-02-04 11:47
Sadly not a duplicate.

**Closed as completed** 2016-02-04 11:47 UTC

**Comment by shearichard** [comment] 2016-02-04 20:52
Excellent ! Thanks for doing the fix.
